[theme]

# Primary accent for interactive elements
primaryColor = '#1FB37E'

# Background color for the main content area
backgroundColor = '#FAF9F6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F9E5BC'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "serif"